import { TypeBook } from "./types/types";

export const books:TypeBook[] = [{
    _id:"thiasfldkajsdfk",
    author:"Dr. R.C Sproul",
    category:"Theology",
    coverImg:"/book-cover/2.jpg",
    description:"this is a description",
    downloads:46,
    file:"/this/asdfasf",
    pages:423,
    pubDate:"12/22/2022",
    title:"How to study Scripture",
    view:65
  },{
    _id:"wertswtsdg",
    author:"Dr. R.C Sproul",
    category:"Theology",
    coverImg:"/book-cover/1.jpeg",
    description:"this is a description",
    downloads:46,
    file:"/this/asdfasf",
    pages:423,
    pubDate:"12/22/2022",
    title:"How to study Scripture",
    view:65
  },{
    _id:"sdfsersdhsdf",
    author:"Dr. R.C Sproul",
    category:"Theology",
    coverImg:"/book-cover/3.jpg",
    description:"this is a description",
    downloads:46,
    file:"/this/asdfasf",
    pages:423,
    pubDate:"12/22/2022",
    title:"How to study Scripture",
    view:65
  },
  {
    _id:"sdfserasdfadsfad",
    author:"Dr. R.C Sproul",
    category:"Theology",
    coverImg:"/book-cover/2.jpg",
    description:"this is a description",
    downloads:46,
    file:"/this/asdfasf",
    pages:423,
    pubDate:"12/22/2022",
    title:"How to study Scripture",
    view:65
  },{
    _id:"thiasfldfdfdkajsdfk",
    author:"Dr. R.C Sproul",
    category:"Theology",
    coverImg:"/book-cover/2.jpg",
    description:"this is a description",
    downloads:46,
    file:"/this/asdfasf",
    pages:423,
    pubDate:"12/22/2022",
    title:"How to study Scripture",
    view:65
  },{
    _id:"wertsaawtsdg",
    author:"Dr. R.C Sproul",
    category:"Theology",
    coverImg:"/book-cover/1.jpeg",
    description:"this is a description",
    downloads:46,
    file:"/this/asdfasf",
    pages:423,
    pubDate:"12/22/2022",
    title:"How to study Scripture",
    view:65
  },{
    _id:"sdfsedfadrsdhsdf",
    author:"Dr. R.C Sproul",
    category:"Theology",
    coverImg:"/book-cover/3.jpg",
    description:"this is a description",
    downloads:46,
    file:"/this/asdfasf",
    pages:423,
    pubDate:"12/22/2022",
    title:"How to study Scripture",
    view:65
  },
  {
    _id:"sdfserasdsdfdfadsfad",
    author:"Dr. R.C Sproul",
    category:"Theology",
    coverImg:"/book-cover/2.jpg",
    description:"this is a description",
    downloads:46,
    file:"/this/asdfasf",
    pages:423,
    pubDate:"12/22/2022",
    title:"How to study Scripture",
    view:65
  },
  ]